title: Software Development Manager
sitename: koyeliroy
logo: /assets/logo/royforge-logo.svg
description: > # this means to ignore newlines until "plugins:"
  Koyeli Roy is a Software Development Manager, having deep rooted experience in 
  development and delivery of digital technology for tier 1 telecom companies globally.

plugins:
 - jekyll-feed
 - jekyll-seo-tag

menu:
  - title: royforge
    url: https://royforge.github.io/

cv:
  name: "Koyeli Roy"
  tagline: "Software Development Manager"
  photo: "/assets/profilepic/koyeli-roy-profile-pic-white-bg.png"
  contact:
    email: "koyeliroy.in@gmail.com"
    mobile: "+91 9423076306"
    location: 
      streetAddress: Magarpatta City
      addressLocality: Pune
      addressRegion: Maharashtra
      addressCountry: IN
      postalCode: 411013
    github: "https://github.com/koyeliroy"
    blog: "https://medium.com/@koyeliroy"
    website: "https://royforge.github.io/"
    linkedin: "https://www.linkedin.com/in/koyeliroy"
  experience:
  - lastpositionheld: Software Development Manager
    company: "Amdocs"
    location: "Pune, IN"
    starttoenddate: "07/2005 - till date"
    achievements: 
    - "Rose through the ranks in the organisation by experiencing nuances of each and every position in the hierarchy."
    - "Delivered complex Customer Service Management and Billing solutions for tier 1 Mobile Operators in the USA."
    - "Awarded Amdocs Delivery Award for completing complex large scale CSM/Billing platform migration project."
    positionsheld:
    - title: "Software Development Manager"
      starttoenddate: "08/2017 - till date"
    - title: "Group Lead"
      starttoenddate: "05/2011 - 07/2017"
    - title: "Senior Subject Matter Expert"
      starttoenddate: "07/2007 - 04/2011"
    - title: "Subject Matter Expert"
      starttoenddate: "07/2005 - 06/2007"
  education:
  - degree: "MS - Computer Software Engineering"
    institute: "Birla Institute of Technology and Science"
    location: "Pilani, IN"
    starttoenddate: "07/2007 - 06/2009"
  - degree: "Bachelors of Engineering - Computer Science"
    institute: "Faculty Of Technology And Engineering (M.S. University of Baroda)"
    location: "Vadodara, IN"
    starttoenddate: "06/2001 - 05/2005"
  certification:
#  - name: "CAKD"
#    id: "987654321"
#    certdate: "05 March 2020"
#  - name: "AWS"
#    id: "132457689"
#    certdate: "20 March 2020"
  skillset:
  - "Technical Leadership"
  - "Team Management"
  - "Project Management"
  - "Delivery Management"
  - "Agile Practices"
  - "SAFe"
  - "Software Architecture"
  - "Amdocs Ensemble"
  - "Java"
  - "Pro*C"
  - "PL SQL"
  retrospection:
  - title: Software Delivery Excellence
    description: Over a period of time, honed software delivery in the organisaion by establishing flexible team structures, empowering teams to take faster decisions and sharpening processes and tools to support modern software development practices. 
  - title: Amdocs Ensemble Subject Matter Expertice
    description: Achieved a very high level of expertise in Amdocs Ensemble CSM and Billing software platforms while delivering to tier one mobile operators in the USA.
  anticipation:
  - title: Empowering Women in Tech
    description: Contribute towards building local community and meetup group to empower women in tech by facilitating mentorship and networking.
  - title: Nurturing Young Minds
    description: Develop and deliver contents to introduce young minds to computing technologies and inculcate coding skills early in life.