title: Software Development Manager
sitename: koyeliroy
logo: /assets/logo/royforge-logo.svg
description: > # this means to ignore newlines until "plugins:"
  Koyeli Roy is a Software Development Manager, having deep rooted experience in 
  development and delivery of digital technology for tier 1 telecom companies globally.

plugins:
 - jekyll-feed
 - jekyll-seo-tag

menu:
  - title: royforge
    url: https://royforge.github.io/

cv:
  name: "Koyeli Roy"
  tagline: "Software Development Manager"
  photo: "/assets/profilepic/koyeli-roy-profile-pic-white-bg.png"
  contact:
    email: "koyeliroy.in@gmail.com"
    mobile: "+91 9423076306"
    location: 
      streetAddress: Magarpatta City
      addressLocality: Pune
      addressRegion: Maharashtra
      addressCountry: IN
      postalCode: 411013
    github: "https://github.com/koyeliroy"
    blog: "https://medium.com/@koyeliroy"
    website: "https://royforge.github.io/"
    linkedin: "https://www.linkedin.com/in/koyeliroy"
  experience:
  - lastpositionheld: Software Development Manager
    company: "Amdocs"
    location: "Pune, IN"
    starttoenddate: "07/2005 - till date"
    achievements: 
    positionsheld:
    - title: "Software Development Manager"
      starttoenddate: "08/2017 - till date"
    - title: "Group Lead"
      starttoenddate: "05/2011 - 07/2017"
    - title: "Senior Subject Matter Expert"
      starttoenddate: "07/2007 - 04/2011"
    - title: "Subject Matter Expert"
      starttoenddate: "07/2005 - 06/2007"
  education:
  - degree: "MS - Computer Software Engineering"
    institute: "Birla Institute of Technology and Science"
    location: "Pilani, IN"
    starttoenddate: "07/2007 - 06/2009"
  - degree: "Bachelors of Engineering - Computer Science"
    institute: "Faculty Of Technology And Engineering (M.S. University of Baroda)"
    location: "Vadodara, IN"
    starttoenddate: "06/2001 - 05/2005"
  certification:
#  - name: "CAKD"
#    id: "987654321"
#    certdate: "05 March 2020"
#  - name: "AWS"
#    id: "132457689"
#    certdate: "20 March 2020"
  skillset:
  - "Technical Leadership"
  - "Team Management"
  - "Project Management"
  - "Agile Practices"
  - "SAFE"
  - "Software Architecture"
  - "Java"
  retrospection:
  - title: Transformed Business
    description: Contributed/led 20+ GA releases of softwares which changed the way we conduct our daily business.
  - title: Transformed People/Teams
    description: Built teams, organisations 
  anticipation:
  - title: Train Young Minds
    description: Contributed/led 20+ GA releases of softwares which changed the way we conduct our daily business.
  - title: Build Communities
    description: Built teams, organisations